name: YouTube Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'YouTube URL'
        required: true
        type: string
      quality:
        description: 'Video quality like 1080, 720, 480'
        required: true
        default: '720'
        type: string

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install yt-dlp
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Create downloads folder
        run: mkdir -p downloads

      - name: Prepare cookies
        env:
          COOKIES: ${{ secrets.YT_COOKIES }}
        run: |
          echo "$COOKIES" > cookies.txt
        # trest

      - name: Download video
        env:
          URL: ${{ github.event.inputs.url }}
          QUALITY: ${{ github.event.inputs.quality }}
        run: |
          yt-dlp \
            --cookies cookies.txt \
            -f "bestvideo[height<=${QUALITY}]+bestaudio/best" \
            --merge-output-format mp4 \
            -o "downloads/%(title)s.%(ext)s" \
            "$URL"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: youtube-download
          path: downloads
